---
AWSTemplateFormatVersion: "2010-09-09"

Description: S3 Bucket

Metadata:

  AWS::CloudFormation::Interface:
    ParameterLabels:
      BucketName:
        default: Bucket Name
      ParameterName:
        default: Parameter Name
    ParameterGroups:
      - Label:
          default: S3
        Parameters:
          - BucketName
      - Label:
          default: SSM
        Parameters:
          - ParameterName

Parameters:
  BucketName:
    Type: String
    Default: ""

  ParameterName:
    Type: String
    Description: (Optional) Name of an SSM parameter to store the bucket name
    Default: ""

Conditions:
  GenerateName: !Equals [!Ref BucketName, ""]
  GenerateParameter: !Not [!Equals [!Ref ParameterName, ""]]

Resources:
  S3Bucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - GenerateName
        - !Ref AWS::NoValue
        - !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: NonCurrentVersionHandling
            Status: Enabled
            NoncurrentVersionExpirationInDays: 90

  SSMParameter:
    Condition: GenerateParameter
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Ref ParameterName
      Value: !Ref S3Bucket

Outputs:
  BucketName:
    Description: Bucket name
    Value: !Ref S3Bucket
  BucketArn:
    Description: Bucket ARN
    Value: !GetAtt S3Bucket.Arn
  SSMParameterName:
    Condition: GenerateParameter
    Description: Name of the SSM parameter
    Value: !Ref SSMParameter
