---
AWSTemplateFormatVersion: "2010-09-09"

Description: S3 bucket, DynamoDB table, and KMS key for Terraform remote state

Metadata:

  AWS::CloudFormation::Interface:
    ParameterLabels:
      TableName:
        default: Table Name
      BucketName:
        default: Bucket Name
      KeyName:
        default: Key Name
      BucketParameterName:
        default: Bucket Parameter Name
      TableParameterName:
        default: Table Parameter Name
      KeyParameterName:
        default: Table Parameter Name
    ParameterGroups:
      - Label:
          default: Configuration
        Parameters:
          - BucketName
          - TableName
          - KeyName
          - BucketParameterName
          - TableParameterName
          - KeyParameterName

Parameters:
  BucketName:
    Description: Name of the S3 bucket
    Type: String
    Default: ""

  TableName:
    Description: Name of the DynamoDB table
    Type: String
    Default: "tfstate-lock"

  KeyName:
    Description: Name of the KMS key in `alias/<KeyName>`
    Type: String
    Default: "tfstate"

  BucketParameterName:
    Type: String
    Description: (Optional) Name of an SSM parameter to store the bucket name
    Default: ""

  TableParameterName:
    Type: String
    Description: (Optional) Name of an SSM parameter to store the table name
    Default: ""

  KeyParameterName:
    Type: String
    Description: (Optional) Name of an SSM parameter to store the key name
    Default: ""



Conditions:
  GenerateBucketName: !Equals [!Ref BucketName, ""]
  GenerateTableName: !Equals [!Ref TableName, ""]
  GenerateBucketParameter: !Not [!Equals [!Ref BucketParameterName, ""]]
  GenerateTableParameter: !Not [!Equals [!Ref TableParameterName, ""]]
  GenerateKeyParameter: !Not [!Equals [!Ref KeyParameterName, ""]]

Resources:

  KmsKey:
    Type: AWS::KMS::Key
    DeletionPolicy: Retain
    Properties:
      Description: "KMS key for S3 encryption"
      KeyPolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource: "*"

  KeyAlias:
    Type: AWS::KMS::Alias
    DeletionPolicy: Retain
    Properties:
      AliasName: !Sub "alias/${KeyName}"
      TargetKeyId: !Ref KmsKey

  S3Bucket:
    DeletionPolicy: Retain
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !If
        - GenerateBucketName
        - !Ref AWS::NoValue
        - !Ref BucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "aws:kms"
              KMSMasterKeyID: !Ref KeyAlias
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: NonCurrentVersionHandling
            Status: Enabled
            NoncurrentVersionExpirationInDays: 365

  DbTable:
    DeletionPolicy: Retain
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If
        - GenerateTableName
        - !Ref AWS::NoValue
        - !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: LockID
          AttributeType: S
      KeySchema:
        - AttributeName: LockID
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      SSESpecification:
        SSEEnabled: true

  BucketParameter:
    Condition: GenerateBucketParameter
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Ref BucketParameterName
      Value: !Ref S3Bucket

  TableParameter:
    Condition: GenerateTableParameter
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Ref TableParameterName
      Value: !Ref DbTable

  KeyParameter:
    Condition: GenerateKeyParameter
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Ref KeyParameterName
      Value: !Ref KeyName

Outputs:
  BucketName:
    Description: S3 bucket name
    Value: !Ref S3Bucket
  BucketArn:
    Description: S3 bucket ARN
    Value: !GetAtt S3Bucket.Arn
  DbTableName:
    Description: DynamoDB table name
    Value: !Ref DbTable
  DbTableArn:
    Description: DynamoDB table ARN
    Value: !GetAtt DbTable.Arn
  KeyAlias:
    Description: KMS Key alias
    Value: !Ref KeyAlias
  BucketParameterName:
    Condition: GenerateBucketParameter
    Description: Name of the SSM parameter
    Value: !Ref BucketParameter
  TableParameterName:
    Condition: GenerateTableParameter
    Description: Name of the SSM parameter
    Value: !Ref TableParameter
  KeyParameterName:
    Condition: GenerateKeyParameter
    Description: Name of the SSM parameter
    Value: !Ref KeyParameter
